### ISSUE TITLE
plugin name/directory discrepancy 

### ISSUE THREAD

**Issue by benemorius** [rocket-rentals/redmine-gitosis#1]
I suppose I am the first to try this as a plugin? Perhaps just the first to try and report back.

lib/gitosis.rb:
      # commands

```
  - ENV['GIT_SSH'] = SSH_WITH_IDENTITY_FILE = File.join(RAILS_ROOT, 'vendor/plugins/redmine_gitosis/extra/ssh_with_identity_file.sh')
  + ENV['GIT_SSH'] = SSH_WITH_IDENTITY_FILE = File.join(RAILS_ROOT, 'vendor/plugins/redmine-gitosis/extra/ssh_with_identity_file.sh')
```

That's the directory it will end up in by default for us since that's how your git repo is named. Other than that I believe I can say it works just fine in a clean environment. A few short words in the readme about configuration would make it an entirely painless install I think.

**Comment by lexxdark** [comment]
You will have problems with the translations if you don't use _. At least I had them, and I decided to change the dir name, rather than to haunt down all the changes I should do in the code.

**Comment by yeah** [comment]
the _ naming of dirs is pretty standard among all plugins, so I'd rather go with that..
