### ISSUE TITLE
Disable Other SCM - Why?

### ISSUE THREAD

**Issue by s0undt3ch** [rocket-rentals/redmine-gitosis#13]
Why does this plugin disable any other SCM?

**Comment by s0undt3ch** [comment]
This for me is a bug. It should simply manage projects with git repositories, and let any other projects, not using git to use whatever they wish.

**Comment by sebix** [comment]
Last activity was on April 18, 2010. I don't think rocket-rentals will react on this issue

See https://github.com/rocket-rentals/redmine-gitosis/network for alternatives

**Comment by s0undt3ch** [comment]
Yeah, Thanks! I found one.
