### ISSUE TITLE
key.identifier has not id

### ISSUE THREAD

**Issue by sars** [rocket-rentals/redmine-gitosis#3]
Hi all.
name of key files consists of user.login.underscore, title.underscore and id, but id is not defined yet
therefore file naming seems to be broken :
username-title-
username-title2-
...

Had anyone faced this problem?

**Comment by yeah** [comment]
yeah, seems to not do what it's supposed to in this release but should work nevertheless... if you like, you can define your own identifiers in GitosisPublicKey#set_identifier
