### ISSUE TITLE
problem create a new project

### ISSUE THREAD

**Issue by vixlima** [rocket-rentals/redmine-gitosis#5]
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your redMine administrator for assistance.

---

Processing ProjectsController#add (for 192.168.0.11 at 2008-10-02 23:18:26) [POST]
  Parameters: {"enabled_modules"=>["issue_tracking", "time_tracking", "news", "documents", "files", "wiki", "repository", "boards"], "commit"=>"Save", "action"=>"add", "authenticity_token"=>"fE5nAN4b8fuCUGalwpKOvY2yK8QgQlN4C+3mQQDT61Q=", "project"=>{"name"=>"new project test", "tracker_ids"=>["1", "2", "3", ""], "homepage"=>"", "parent_id"=>"", "is_public"=>"1", "description"=>"", "identifier"=>"monkey"}, "controller"=>"projects"}

Errno::ENOENT (No such file or directory - /tmp/redmine-gitosis-1223000306/gitosis/gitosis.conf):
  inifile (0.3.0) lib/inifile.rb:67:in `initialize'
  inifile (0.3.0) lib/inifile.rb:67:in`open'
  inifile (0.3.0) lib/inifile.rb:67:in `write'
  /usr/lib/ruby/1.8/lockfile.rb:284:in`lock'
  /usr/lib/ruby/1.8/lockfile.rb:539:in `attempt'
  /usr/lib/ruby/1.8/lockfile.rb:539:in`catch'
  /usr/lib/ruby/1.8/lockfile.rb:539:in `attempt'
  /usr/lib/ruby/1.8/lockfile.rb:539:in`loop'
  /usr/lib/ruby/1.8/lockfile.rb:539:in `attempt'
  /usr/lib/ruby/1.8/lockfile.rb:210:in`lock'
  /usr/lib/ruby/1.8/lockfile.rb:199:in `initialize'
  /usr/lib/ruby/1.8/lockfile.rb:559:in`new'
  /usr/lib/ruby/1.8/lockfile.rb:559:in `Lockfile'
  vendor/plugins/redmine_gitosis/app/models/gitosis_observer.rb:21:in`update_repositories'
  vendor/plugins/redmine_gitosis/app/models/gitosis_observer.rb:13:in `after_save'
  /usr/lib/ruby/1.8/observer.rb:185:in`notify_observers'
  /usr/lib/ruby/1.8/observer.rb:184:in `each'
  /usr/lib/ruby/1.8/observer.rb:184:in`notify_observers'
  app/controllers/projects_controller.rb:78:in `add'
  passenger (2.2.11) lib/phusion_passenger/rack/request_handler.rb:92:in`process_request'
  passenger (2.2.11) lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  passenger (2.2.11) lib/phusion_passenger/railz/application_spawner.rb:418:in`start_request_handler'
  passenger (2.2.11) lib/phusion_passenger/railz/application_spawner.rb:358:in `handle_spawn_application'
  passenger (2.2.11) lib/phusion_passenger/utils.rb:184:in`safe_fork'
  passenger (2.2.11) lib/phusion_passenger/railz/application_spawner.rb:354:in `handle_spawn_application'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:352:in`**send**'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:163:in `start'
  passenger (2.2.11) lib/phusion_passenger/railz/application_spawner.rb:213:in`start'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  passenger (2.2.11) lib/phusion_passenger/abstract_server_collection.rb:126:in`lookup_or_add'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  passenger (2.2.11) lib/phusion_passenger/abstract_server_collection.rb:80:in`synchronize'
  passenger (2.2.11) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:255:in`spawn_rails_application'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:287:in`handle_spawn_application'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:352:in`main_loop'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'

Rendering /home/railsapps/redmine.eximbiz.com.br/public/500.html (500 Internal Server Error)

**Comment by lars-derichter** [comment]
Same here. Any solutions?
